### ISSUE TITLE
你好，能请问一下，你这个文字是怎么识别的吗？求教，谢谢

### ISSUE THREAD

**Issue by cpy1989** [janlle/12306#1]

**Comment by janlle** [comment]
使用Tensorflow训练模型数据（12306验证码）得到的AI模型

**Comment by cpy1989** [comment]
你直接用文字数据集来训练的？ 然后得到ai模型，再识别出文字 ？
那你的文字数据集能给我一份吗，谢谢

**Comment by janlle** [comment]
使用的是图片数据集，我没有训练过，感兴趣你可以参考 https://github.com/andelf/fuck12306

**Comment by cpy1989** [comment]
好吧，他这个识别率不高

**Comment by janlle** [comment]
好吧，这个识别精准度和模型的训练有很大关系

**Comment by cpy1989** [comment]
关键是不知道思路，文字识别是怎么弄的？  我现在8张图片是可以识别出来的
